# general description
title:              farpras28
subtitle:           I eat Indomie a lot.
description:        

# site settings
baseurl:
url:                http://repo.farpras.id
permalink:          /:categories/:title

# social
twitter_username:   farpras
github_username:    farpras28
facebook_username:  
email:              farpras28@outlook.com

# build settings
markdown:           kramdown
kramdown:
  input:            GFM
  hard_wrap:        false
  highlighter:      rouge
sass:
  style:            :compressed
exclude:            ['LICENSE', 'README.md']
